package(default_visibility = ["//visibility:public"])

filegroup(
    name = "models",
    srcs = glob(["*.tflite"]),
)

filegroup(
    name = "images",
    srcs = glob(["*.bmp"]),
)

filegroup(
    name = "reference_results",
    srcs = glob(["*.csv"]),
)
